// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AccessiblePeer struct {
	// Peer's DNS label is the parsed peer name for domain resolution. It is used to form an FQDN by appending the account's domain to the peer label. e.g. peer-dns-label.netbird.cloud
	DNSLabel string `json:"dns_label"`
	// Peer ID
	ID string `json:"id"`
	// Peer's IP address
	IP string `json:"ip"`
	// Peer's hostname
	Name string `json:"name"`
	// User ID of the user that enrolled this peer
	UserID string `json:"user_id"`
}

func (o *AccessiblePeer) GetDNSLabel() string {
	if o == nil {
		return ""
	}
	return o.DNSLabel
}

func (o *AccessiblePeer) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AccessiblePeer) GetIP() string {
	if o == nil {
		return ""
	}
	return o.IP
}

func (o *AccessiblePeer) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *AccessiblePeer) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}
