// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Account struct {
	// Account ID
	ID       string          `json:"id"`
	Settings AccountSettings `json:"settings"`
}

func (o *Account) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Account) GetSettings() AccountSettings {
	if o == nil {
		return AccountSettings{}
	}
	return o.Settings
}
