// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AccountRequest - update an account
type AccountRequest struct {
	Settings AccountSettings `json:"settings"`
}
