// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Account struct {
	// Account ID
	ID       string          `json:"id"`
	Settings AccountSettings `json:"settings"`
}
