// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AccountRequest struct {
	Settings AccountSettings `json:"settings"`
}

func (o *AccountRequest) GetSettings() AccountSettings {
	if o == nil {
		return AccountSettings{}
	}
	return o.Settings
}
