// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Checks - List of objects that perform the actual checks
type Checks struct {
	// Posture check for geo location
	GeoLocationCheck *GeoLocationCheck `json:"geo_location_check,omitempty"`
	// Posture check for the version of operating system
	NbVersionCheck *NBVersionCheck `json:"nb_version_check,omitempty"`
	// Posture check for the version of operating system
	OsVersionCheck *OSVersionCheck `json:"os_version_check,omitempty"`
}

func (o *Checks) GetGeoLocationCheck() *GeoLocationCheck {
	if o == nil {
		return nil
	}
	return o.GeoLocationCheck
}

func (o *Checks) GetNbVersionCheck() *NBVersionCheck {
	if o == nil {
		return nil
	}
	return o.NbVersionCheck
}

func (o *Checks) GetOsVersionCheck() *OSVersionCheck {
	if o == nil {
		return nil
	}
	return o.OsVersionCheck
}
