// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// City - Describe city geographical location information
type City struct {
	// Commonly used English name of the city
	CityName string `json:"city_name"`
	// Integer ID of the record in GeoNames database
	GeonameID int64 `json:"geoname_id"`
}

func (o *City) GetCityName() string {
	if o == nil {
		return ""
	}
	return o.CityName
}

func (o *City) GetGeonameID() int64 {
	if o == nil {
		return 0
	}
	return o.GeonameID
}
