// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Country - Describe country geographical location information
type Country struct {
	// 2-letter ISO 3166-1 alpha-2 code that represents the country
	CountryCode string `pathParam:"name=country_code"`
	// Commonly used English name of the country
	CountryName string `pathParam:"name=country_name"`
}

func (o *Country) GetCountryCode() string {
	if o == nil {
		return ""
	}
	return o.CountryCode
}

func (o *Country) GetCountryName() string {
	if o == nil {
		return ""
	}
	return o.CountryName
}
