// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DNSSettings struct {
	// Groups whose DNS management is disabled
	DisabledManagementGroups []string `json:"disabled_management_groups"`
}
