// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Group struct {
	// Group ID
	ID string `json:"id"`
	// How group was issued by API or from JWT token
	Issued *string `json:"issued,omitempty"`
	// Group Name identifier
	Name string `json:"name"`
	// List of peers object
	Peers []PeerMinimum `json:"peers"`
	// Count of peers associated to the group
	PeersCount int64 `json:"peers_count"`
}

func (o *Group) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Group) GetIssued() *string {
	if o == nil {
		return nil
	}
	return o.Issued
}

func (o *Group) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Group) GetPeers() []PeerMinimum {
	if o == nil {
		return []PeerMinimum{}
	}
	return o.Peers
}

func (o *Group) GetPeersCount() int64 {
	if o == nil {
		return 0
	}
	return o.PeersCount
}
