// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GroupRequest struct {
	// Group name identifier
	Name string `json:"name"`
	// List of peers ids
	Peers []string `json:"peers,omitempty"`
}

func (o *GroupRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GroupRequest) GetPeers() []string {
	if o == nil {
		return nil
	}
	return o.Peers
}
