// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Group - A Group Object
type Group struct {
	// Group ID
	ID string `json:"id"`
	// How group was issued by API or from JWT token
	Issued *string `json:"issued,omitempty"`
	// Group Name identifier
	Name string `json:"name"`
	// List of peers object
	Peers []PeerMinimum `json:"peers"`
	// Count of peers associated to the group
	PeersCount int64 `json:"peers_count"`
}
