// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GroupRequest - New Group request
type GroupRequest struct {
	// Group name identifier
	Name string `json:"name"`
	// List of peers ids
	Peers []string `json:"peers,omitempty"`
}
