// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Location - Describe geographical location information
type Location struct {
	// Commonly used English name of the city
	CityName *string `json:"city_name,omitempty"`
	// 2-letter ISO 3166-1 alpha-2 code that represents the country
	CountryCode string `json:"country_code"`
}

func (o *Location) GetCityName() *string {
	if o == nil {
		return nil
	}
	return o.CityName
}

func (o *Location) GetCountryCode() string {
	if o == nil {
		return ""
	}
	return o.CountryCode
}
