// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// NsType - Nameserver Type
type NsType string

const (
	NsTypeUDP NsType = "udp"
)

func (e NsType) ToPointer() *NsType {
	return &e
}

func (e *NsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "udp":
		*e = NsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NsType: %v", v)
	}
}

type Nameserver struct {
	// Nameserver IP
	IP string `json:"ip"`
	// Nameserver Type
	NsType NsType `json:"ns_type"`
	// Nameserver Port
	Port int64 `json:"port"`
}

func (o *Nameserver) GetIP() string {
	if o == nil {
		return ""
	}
	return o.IP
}

func (o *Nameserver) GetNsType() NsType {
	if o == nil {
		return NsType("")
	}
	return o.NsType
}

func (o *Nameserver) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}
