// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// NameserverGroup - A Nameserver Groups Object
type NameserverGroup struct {
	// Nameserver group  description
	Description string `json:"description"`
	// Nameserver group domain list
	Domains []string `json:"domains"`
	// Nameserver group status
	Enabled bool `json:"enabled"`
	// Nameserver group tag groups
	Groups []string `json:"groups"`
	// Nameserver group ID
	ID string `json:"id"`
	// Nameserver group name
	Name string `json:"name"`
	// Nameserver group
	Nameservers []Nameserver `json:"nameservers"`
	// Nameserver group primary status
	Primary bool `json:"primary"`
}
