// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// NameserverGroupRequest - New Nameserver Groups request
type NameserverGroupRequest struct {
	// Nameserver group  description
	Description string `json:"description"`
	// Nameserver group domain list
	Domains []string `json:"domains"`
	// Nameserver group status
	Enabled bool `json:"enabled"`
	// Nameserver group tag groups
	Groups []string `json:"groups"`
	// Nameserver group name
	Name string `json:"name"`
	// Nameserver group
	Nameservers []Nameserver `json:"nameservers"`
	// Nameserver group primary status
	Primary bool `json:"primary"`
}
