// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NameserverGroup struct {
	// Description of the nameserver group
	Description string `json:"description"`
	// Match domain list. It should be empty only if primary is true.
	Domains []string `json:"domains"`
	// Nameserver group status
	Enabled bool `json:"enabled"`
	// Distribution group IDs that defines group of peers that will use this nameserver group
	Groups []string `json:"groups"`
	// Nameserver group ID
	ID string `json:"id"`
	// Name of nameserver group name
	Name string `json:"name"`
	// Nameserver list
	Nameservers []Nameserver `json:"nameservers"`
	// Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
	Primary bool `json:"primary"`
	// Search domain status for match domains. It should be true only if domains list is not empty.
	SearchDomainsEnabled bool `json:"search_domains_enabled"`
}

func (o *NameserverGroup) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *NameserverGroup) GetDomains() []string {
	if o == nil {
		return []string{}
	}
	return o.Domains
}

func (o *NameserverGroup) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *NameserverGroup) GetGroups() []string {
	if o == nil {
		return []string{}
	}
	return o.Groups
}

func (o *NameserverGroup) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *NameserverGroup) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *NameserverGroup) GetNameservers() []Nameserver {
	if o == nil {
		return []Nameserver{}
	}
	return o.Nameservers
}

func (o *NameserverGroup) GetPrimary() bool {
	if o == nil {
		return false
	}
	return o.Primary
}

func (o *NameserverGroup) GetSearchDomainsEnabled() bool {
	if o == nil {
		return false
	}
	return o.SearchDomainsEnabled
}
