// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// NBVersionCheck - Posture check for the version of operating system
type NBVersionCheck struct {
	// Minimum acceptable version
	MinVersion string `json:"min_version"`
}

func (o *NBVersionCheck) GetMinVersion() string {
	if o == nil {
		return ""
	}
	return o.MinVersion
}
