// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// OSVersionCheck - Posture check for the version of operating system
type OSVersionCheck struct {
	// Posture check for the version of operating system
	Android *MinVersionCheck `json:"android,omitempty"`
	// Posture check for the version of operating system
	Darwin *MinVersionCheck `json:"darwin,omitempty"`
	// Posture check for the version of operating system
	Ios *MinVersionCheck `json:"ios,omitempty"`
	// Posture check with the kernel version
	Linux *MinKernelVersionCheck `json:"linux,omitempty"`
	// Posture check with the kernel version
	Windows *MinKernelVersionCheck `json:"windows,omitempty"`
}

func (o *OSVersionCheck) GetAndroid() *MinVersionCheck {
	if o == nil {
		return nil
	}
	return o.Android
}

func (o *OSVersionCheck) GetDarwin() *MinVersionCheck {
	if o == nil {
		return nil
	}
	return o.Darwin
}

func (o *OSVersionCheck) GetIos() *MinVersionCheck {
	if o == nil {
		return nil
	}
	return o.Ios
}

func (o *OSVersionCheck) GetLinux() *MinKernelVersionCheck {
	if o == nil {
		return nil
	}
	return o.Linux
}

func (o *OSVersionCheck) GetWindows() *MinKernelVersionCheck {
	if o == nil {
		return nil
	}
	return o.Windows
}
