// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PeerMinimum struct {
	// Peer ID
	ID string `json:"id"`
	// Peer's hostname
	Name string `json:"name"`
}

func (o *PeerMinimum) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PeerMinimum) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
