// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type Peer struct {
	// Peer to Management connection status
	Connected bool `json:"connected"`
	// Peer's DNS label is the parsed peer name for domain resolution. It is used to form an FQDN by appending the account's domain to the peer label. e.g. peer-dns-label.netbird.cloud
	DNSLabel string `json:"dns_label"`
	// Groups that the peer belongs to
	Groups []GroupMinimum `json:"groups"`
	// Hostname of the machine
	Hostname string `json:"hostname"`
	// Peer ID
	ID string `json:"id"`
	// Peer's IP address
	IP string `json:"ip"`
	// Last time this peer performed log in (authentication). E.g., user authenticated.
	LastLogin time.Time `json:"last_login"`
	// Last time peer connected to Netbird's management service
	LastSeen time.Time `json:"last_seen"`
	// Indicates whether peer login expiration has been enabled or not
	LoginExpirationEnabled bool `json:"login_expiration_enabled"`
	// Indicates whether peer's login expired or not
	LoginExpired bool `json:"login_expired"`
	// Peer's hostname
	Name string `json:"name"`
	// Peer's operating system and version
	Os string `json:"os"`
	// Indicates whether SSH server is enabled on this peer
	SSHEnabled bool `json:"ssh_enabled"`
	// Peer's desktop UI version
	UIVersion *string `json:"ui_version,omitempty"`
	// User ID of the user that enrolled this peer
	UserID *string `json:"user_id,omitempty"`
	// Peer's daemon or cli version
	Version string `json:"version"`
}
