// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PeerRequest struct {
	LoginExpirationEnabled bool   `json:"login_expiration_enabled"`
	Name                   string `json:"name"`
	SSHEnabled             bool   `json:"ssh_enabled"`
}
