// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PeerNetworkRangeCheckAction - Action to take upon policy match
type PeerNetworkRangeCheckAction string

const (
	PeerNetworkRangeCheckActionAllow PeerNetworkRangeCheckAction = "allow"
	PeerNetworkRangeCheckActionDeny  PeerNetworkRangeCheckAction = "deny"
)

func (e PeerNetworkRangeCheckAction) ToPointer() *PeerNetworkRangeCheckAction {
	return &e
}

func (e *PeerNetworkRangeCheckAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "allow":
		fallthrough
	case "deny":
		*e = PeerNetworkRangeCheckAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PeerNetworkRangeCheckAction: %v", v)
	}
}

// PeerNetworkRangeCheck - Posture check for allow or deny access based on peer local network addresses
type PeerNetworkRangeCheck struct {
	// Action to take upon policy match
	Action PeerNetworkRangeCheckAction `json:"action"`
	// List of peer network ranges in CIDR notation
	Ranges []string `json:"ranges"`
}

func (o *PeerNetworkRangeCheck) GetAction() PeerNetworkRangeCheckAction {
	if o == nil {
		return PeerNetworkRangeCheckAction("")
	}
	return o.Action
}

func (o *PeerNetworkRangeCheck) GetRanges() []string {
	if o == nil {
		return []string{}
	}
	return o.Ranges
}
