// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PeerRequest struct {
	LoginExpirationEnabled bool   `json:"login_expiration_enabled"`
	Name                   string `json:"name"`
	SSHEnabled             bool   `json:"ssh_enabled"`
}

func (o *PeerRequest) GetLoginExpirationEnabled() bool {
	if o == nil {
		return false
	}
	return o.LoginExpirationEnabled
}

func (o *PeerRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PeerRequest) GetSSHEnabled() bool {
	if o == nil {
		return false
	}
	return o.SSHEnabled
}
