// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PersonalAccessTokenRequest struct {
	// Expiration in days
	ExpiresIn int64 `json:"expires_in"`
	// Name of the token
	Name string `json:"name"`
}
