// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PersonalAccessTokenRequest struct {
	// Expiration in days
	ExpiresIn int64 `json:"expires_in"`
	// Name of the token
	Name string `json:"name"`
}

func (o *PersonalAccessTokenRequest) GetExpiresIn() int64 {
	if o == nil {
		return 0
	}
	return o.ExpiresIn
}

func (o *PersonalAccessTokenRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
