// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PersonalAccessTokenGenerated - The token in plain text
type PersonalAccessTokenGenerated struct {
	PersonalAccessToken PersonalAccessToken `json:"personal_access_token"`
	// Plain text representation of the generated token
	PlainToken string `json:"plain_token"`
}
