// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PersonalAccessTokenGenerated struct {
	PersonalAccessToken PersonalAccessToken `json:"personal_access_token"`
	// Plain text representation of the generated token
	PlainToken string `json:"plain_token"`
}

func (o *PersonalAccessTokenGenerated) GetPersonalAccessToken() PersonalAccessToken {
	if o == nil {
		return PersonalAccessToken{}
	}
	return o.PersonalAccessToken
}

func (o *PersonalAccessTokenGenerated) GetPlainToken() string {
	if o == nil {
		return ""
	}
	return o.PlainToken
}
