// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type PersonalAccessToken struct {
	// Date the token was created
	CreatedAt time.Time `json:"created_at"`
	// User ID of the user who created the token
	CreatedBy string `json:"created_by"`
	// Date the token expires
	ExpirationDate time.Time `json:"expiration_date"`
	// ID of a token
	ID string `json:"id"`
	// Date the token was last used
	LastUsed *time.Time `json:"last_used,omitempty"`
	// Name of the token
	Name string `json:"name"`
}
