// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Policy struct {
	// Policy friendly description
	Description string `json:"description"`
	// Policy status
	Enabled bool `json:"enabled"`
	// Policy ID
	ID *string `json:"id,omitempty"`
	// Policy name identifier
	Name string `json:"name"`
	// Policy rule object for policy UI editor
	Rules []PolicyRule `json:"rules"`
	// Posture checks ID's applied to policy source groups
	SourcePostureChecks []string `json:"source_posture_checks"`
}

func (o *Policy) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *Policy) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *Policy) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Policy) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Policy) GetRules() []PolicyRule {
	if o == nil {
		return []PolicyRule{}
	}
	return o.Rules
}

func (o *Policy) GetSourcePostureChecks() []string {
	if o == nil {
		return []string{}
	}
	return o.SourcePostureChecks
}
