// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PostureCheckUpdate struct {
	// List of objects that perform the actual checks
	Checks *Checks `json:"checks,omitempty"`
	// Posture check friendly description
	Description string `json:"description"`
	// Posture check name identifier
	Name string `json:"name"`
}

func (o *PostureCheckUpdate) GetChecks() *Checks {
	if o == nil {
		return nil
	}
	return o.Checks
}

func (o *PostureCheckUpdate) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *PostureCheckUpdate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
