// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PostureCheck struct {
	// List of objects that perform the actual checks
	Checks Checks `json:"checks"`
	// Posture check friendly description
	Description *string `json:"description,omitempty"`
	// Posture check ID
	ID string `json:"id"`
	// Posture check unique name identifier
	Name string `json:"name"`
}

func (o *PostureCheck) GetChecks() Checks {
	if o == nil {
		return Checks{}
	}
	return o.Checks
}

func (o *PostureCheck) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PostureCheck) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PostureCheck) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
