// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RouteRequest struct {
	// Route description
	Description string `json:"description"`
	// Route status
	Enabled bool `json:"enabled"`
	// Route group tag groups
	Groups []string `json:"groups"`
	// Indicate if peer should masquerade traffic to this route's prefix
	Masquerade bool `json:"masquerade"`
	// Route metric number. Lowest number has higher priority
	Metric int64 `json:"metric"`
	// Network range in CIDR format
	Network string `json:"network"`
	// Route network identifier, to group HA routes
	NetworkID string `json:"network_id"`
	// Peer Identifier associated with route. This property can not be set together with `peer_groups`
	Peer *string `json:"peer,omitempty"`
	// Peers Group Identifier associated with route. This property can not be set together with `peer`
	PeerGroups []string `json:"peer_groups,omitempty"`
}
