// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RuleRequest - New Rule request
type RuleRequest struct {
	// Rule friendly description
	Description string `json:"description"`
	// List of destination groups
	Destinations []string `json:"destinations,omitempty"`
	// Rules status
	Disabled bool `json:"disabled"`
	// Rule flow, currently, only "bidirect" for bi-directional traffic is accepted
	Flow string `json:"flow"`
	// Rule name identifier
	Name string `json:"name"`
	// List of source groups
	Sources []string `json:"sources,omitempty"`
}
