// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserCreateRequest - User invite information
type UserCreateRequest struct {
	// Groups to auto-assign to peers registered by this user
	AutoGroups []string `json:"auto_groups"`
	// User's Email to send invite to
	Email *string `json:"email,omitempty"`
	// Is true if this user is a service user
	IsServiceUser bool `json:"is_service_user"`
	// User's full name
	Name *string `json:"name,omitempty"`
	// User's NetBird account role
	Role string `json:"role"`
}
