// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UserCreateRequest struct {
	// Groups to auto-assign to peers registered by this user
	AutoGroups []string `json:"auto_groups"`
	// User's Email to send invite to
	Email *string `json:"email,omitempty"`
	// Is true if this user is a service user
	IsServiceUser bool `json:"is_service_user"`
	// User's full name
	Name *string `json:"name,omitempty"`
	// User's NetBird account role
	Role string `json:"role"`
}

func (o *UserCreateRequest) GetAutoGroups() []string {
	if o == nil {
		return []string{}
	}
	return o.AutoGroups
}

func (o *UserCreateRequest) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UserCreateRequest) GetIsServiceUser() bool {
	if o == nil {
		return false
	}
	return o.IsServiceUser
}

func (o *UserCreateRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UserCreateRequest) GetRole() string {
	if o == nil {
		return ""
	}
	return o.Role
}
