// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIPostureChecksPostureCheckIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *DeleteAPIPostureChecksPostureCheckIDSecurity) GetBearerAuth() *string {
	if o == nil {
		return nil
	}
	return o.BearerAuth
}

func (o *DeleteAPIPostureChecksPostureCheckIDSecurity) GetTokenAuth() *string {
	if o == nil {
		return nil
	}
	return o.TokenAuth
}

type DeleteAPIPostureChecksPostureCheckIDRequest struct {
	// The unique identifier of a posture check
	PostureCheckID string `pathParam:"style=simple,explode=false,name=postureCheckId"`
}

func (o *DeleteAPIPostureChecksPostureCheckIDRequest) GetPostureCheckID() string {
	if o == nil {
		return ""
	}
	return o.PostureCheckID
}

type DeleteAPIPostureChecksPostureCheckIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteAPIPostureChecksPostureCheckIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteAPIPostureChecksPostureCheckIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteAPIPostureChecksPostureCheckIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
