// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIUsersUserIDTokensTokenIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *DeleteAPIUsersUserIDTokensTokenIDSecurity) GetBearerAuth() *string {
	if o == nil {
		return nil
	}
	return o.BearerAuth
}

func (o *DeleteAPIUsersUserIDTokensTokenIDSecurity) GetTokenAuth() *string {
	if o == nil {
		return nil
	}
	return o.TokenAuth
}

type DeleteAPIUsersUserIDTokensTokenIDRequest struct {
	// The unique identifier of a token
	TokenID string `pathParam:"style=simple,explode=false,name=tokenId"`
	// The unique identifier of a user
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

func (o *DeleteAPIUsersUserIDTokensTokenIDRequest) GetTokenID() string {
	if o == nil {
		return ""
	}
	return o.TokenID
}

func (o *DeleteAPIUsersUserIDTokensTokenIDRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type DeleteAPIUsersUserIDTokensTokenIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteAPIUsersUserIDTokensTokenIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteAPIUsersUserIDTokensTokenIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteAPIUsersUserIDTokensTokenIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
