// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIPoliciesPolicyIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type DeleteAPIPoliciesPolicyIDRequest struct {
	// The unique identifier of a policy
	PolicyID string `pathParam:"style=simple,explode=false,name=policyId"`
}

type DeleteAPIPoliciesPolicyIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
