// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type GetAPIGroupsGroupIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type GetAPIGroupsGroupIDRequest struct {
	// The unique identifier of a group
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
}

type GetAPIGroupsGroupIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A Group object
	Group *shared.Group
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
