// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/v2/internal/sdk/pkg/models/shared"
)

type GetAPIGroupsGroupIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *GetAPIGroupsGroupIDSecurity) GetBearerAuth() *string {
	if o == nil {
		return nil
	}
	return o.BearerAuth
}

func (o *GetAPIGroupsGroupIDSecurity) GetTokenAuth() *string {
	if o == nil {
		return nil
	}
	return o.TokenAuth
}

type GetAPIGroupsGroupIDRequest struct {
	// The unique identifier of a group
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
}

func (o *GetAPIGroupsGroupIDRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

type GetAPIGroupsGroupIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A Group object
	Group *shared.Group
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAPIGroupsGroupIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIGroupsGroupIDResponse) GetGroup() *shared.Group {
	if o == nil {
		return nil
	}
	return o.Group
}

func (o *GetAPIGroupsGroupIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIGroupsGroupIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
