// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type GetAPIUsersUserIDTokensSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type GetAPIUsersUserIDTokensRequest struct {
	// The unique identifier of a user
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type GetAPIUsersUserIDTokensResponse struct {
	ContentType string
	// A JSON Array of PersonalAccessTokens
	PersonalAccessTokens []shared.PersonalAccessToken
	StatusCode           int
	RawResponse          *http.Response
}
