// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type GetAPIUsersUserIDTokensTokenIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type GetAPIUsersUserIDTokensTokenIDRequest struct {
	// The unique identifier of a token
	TokenID string `pathParam:"style=simple,explode=false,name=tokenId"`
	// The unique identifier of a user
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type GetAPIUsersUserIDTokensTokenIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A PersonalAccessTokens Object
	PersonalAccessToken *shared.PersonalAccessToken
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
