// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/NetBird/terraform-provider-netbird/v4/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetAPILocationsCountriesCountryCitiesSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *GetAPILocationsCountriesCountryCitiesSecurity) GetBearerAuth() *string {
	if o == nil {
		return nil
	}
	return o.BearerAuth
}

func (o *GetAPILocationsCountriesCountryCitiesSecurity) GetTokenAuth() *string {
	if o == nil {
		return nil
	}
	return o.TokenAuth
}

type GetAPILocationsCountriesCountryCitiesRequest struct {
	// Describe country geographical location information
	Country shared.Country `pathParam:"style=simple,explode=false,name=country"`
}

func (o *GetAPILocationsCountriesCountryCitiesRequest) GetCountry() shared.Country {
	if o == nil {
		return shared.Country{}
	}
	return o.Country
}

type GetAPILocationsCountriesCountryCitiesResponse struct {
	// List of city names
	City *shared.City
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAPILocationsCountriesCountryCitiesResponse) GetCity() *shared.City {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *GetAPILocationsCountriesCountryCitiesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPILocationsCountriesCountryCitiesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPILocationsCountriesCountryCitiesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
