// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/NetBird/terraform-provider-netbird/v4/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetAPIPostureChecksPostureCheckIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *GetAPIPostureChecksPostureCheckIDSecurity) GetBearerAuth() *string {
	if o == nil {
		return nil
	}
	return o.BearerAuth
}

func (o *GetAPIPostureChecksPostureCheckIDSecurity) GetTokenAuth() *string {
	if o == nil {
		return nil
	}
	return o.TokenAuth
}

type GetAPIPostureChecksPostureCheckIDRequest struct {
	// The unique identifier of a posture check
	PostureCheckID string `pathParam:"style=simple,explode=false,name=postureCheckId"`
}

func (o *GetAPIPostureChecksPostureCheckIDRequest) GetPostureCheckID() string {
	if o == nil {
		return ""
	}
	return o.PostureCheckID
}

type GetAPIPostureChecksPostureCheckIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A posture check object
	PostureCheck *shared.PostureCheck
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAPIPostureChecksPostureCheckIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIPostureChecksPostureCheckIDResponse) GetPostureCheck() *shared.PostureCheck {
	if o == nil {
		return nil
	}
	return o.PostureCheck
}

func (o *GetAPIPostureChecksPostureCheckIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIPostureChecksPostureCheckIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
