// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type GetAPIRulesRuleIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type GetAPIRulesRuleIDRequest struct {
	// The unique identifier of a rule
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
}

type GetAPIRulesRuleIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A Rule object
	Rule *shared.Rule
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
