// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/v2/internal/sdk/pkg/models/shared"
)

type GetAPISetupKeysKeyIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *GetAPISetupKeysKeyIDSecurity) GetBearerAuth() *string {
	if o == nil {
		return nil
	}
	return o.BearerAuth
}

func (o *GetAPISetupKeysKeyIDSecurity) GetTokenAuth() *string {
	if o == nil {
		return nil
	}
	return o.TokenAuth
}

type GetAPISetupKeysKeyIDRequest struct {
	// The unique identifier of a setup key
	KeyID string `pathParam:"style=simple,explode=false,name=keyId"`
}

func (o *GetAPISetupKeysKeyIDRequest) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

type GetAPISetupKeysKeyIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A Setup Key object
	SetupKey *shared.SetupKey
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAPISetupKeysKeyIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPISetupKeysKeyIDResponse) GetSetupKey() *shared.SetupKey {
	if o == nil {
		return nil
	}
	return o.SetupKey
}

func (o *GetAPISetupKeysKeyIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPISetupKeysKeyIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
