// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type PostAPIUsersUserIDTokensSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type PostAPIUsersUserIDTokensRequest struct {
	// PersonalAccessToken create parameters
	PersonalAccessTokenRequest *shared.PersonalAccessTokenRequest `request:"mediaType=application/json"`
	// The unique identifier of a user
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type PostAPIUsersUserIDTokensResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The token in plain text
	PersonalAccessTokenGenerated *shared.PersonalAccessTokenGenerated
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
