// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type PutAPIRoutesRouteIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type PutAPIRoutesRouteIDRequest struct {
	// Update Route request
	RouteRequest *shared.RouteRequest `request:"mediaType=application/json"`
	// The unique identifier of a route
	RouteID string `pathParam:"style=simple,explode=false,name=routeId"`
}

type PutAPIRoutesRouteIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A Route object
	Route *shared.Route
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
