// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/NetBird/terraform-provider-netbird/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type PutAPIAccountsAccountIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *PutAPIAccountsAccountIDSecurity) GetBearerAuth() *string {
	if o == nil {
		return nil
	}
	return o.BearerAuth
}

func (o *PutAPIAccountsAccountIDSecurity) GetTokenAuth() *string {
	if o == nil {
		return nil
	}
	return o.TokenAuth
}

type PutAPIAccountsAccountIDRequest struct {
	// update an account
	AccountRequest *shared.AccountRequest `request:"mediaType=application/json"`
	// The unique identifier of an account
	AccountID string `pathParam:"style=simple,explode=false,name=accountId"`
}

func (o *PutAPIAccountsAccountIDRequest) GetAccountRequest() *shared.AccountRequest {
	if o == nil {
		return nil
	}
	return o.AccountRequest
}

func (o *PutAPIAccountsAccountIDRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

type PutAPIAccountsAccountIDResponse struct {
	// An Account object
	Account *shared.Account
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PutAPIAccountsAccountIDResponse) GetAccount() *shared.Account {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *PutAPIAccountsAccountIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutAPIAccountsAccountIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutAPIAccountsAccountIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
