// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type PutAPISetupKeysKeyIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type PutAPISetupKeysKeyIDRequest struct {
	// update to Setup Key
	SetupKeyRequest *shared.SetupKeyRequest `request:"mediaType=application/json"`
	// The unique identifier of a setup key
	KeyID string `pathParam:"style=simple,explode=false,name=keyId"`
}

type PutAPISetupKeysKeyIDResponse struct {
	ContentType string
	// A Setup Key object
	SetupKey    *shared.SetupKey
	StatusCode  int
	RawResponse *http.Response
}
