// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/NetBird/terraform-provider-netbird/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type PutAPIUsersUserIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (o *PutAPIUsersUserIDSecurity) GetBearerAuth() *string {
	if o == nil {
		return nil
	}
	return o.BearerAuth
}

func (o *PutAPIUsersUserIDSecurity) GetTokenAuth() *string {
	if o == nil {
		return nil
	}
	return o.TokenAuth
}

type PutAPIUsersUserIDRequest struct {
	// User update
	UserRequest *shared.UserRequest `request:"mediaType=application/json"`
	// The unique identifier of a user
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

func (o *PutAPIUsersUserIDRequest) GetUserRequest() *shared.UserRequest {
	if o == nil {
		return nil
	}
	return o.UserRequest
}

func (o *PutAPIUsersUserIDRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type PutAPIUsersUserIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A User object
	User *shared.User
}

func (o *PutAPIUsersUserIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutAPIUsersUserIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutAPIUsersUserIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PutAPIUsersUserIDResponse) GetUser() *shared.User {
	if o == nil {
		return nil
	}
	return o.User
}
