// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type PutAPIAccountsAccountIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type PutAPIAccountsAccountIDRequest struct {
	// update an account
	AccountRequest *shared.AccountRequest `request:"mediaType=application/json"`
	// The unique identifier of an account
	AccountID string `pathParam:"style=simple,explode=false,name=accountId"`
}

type PutAPIAccountsAccountIDResponse struct {
	// An Account object
	Account     *shared.Account
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
