// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type PutAPIDNSSettingsSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type PutAPIDNSSettingsResponse struct {
	ContentType string
	// A JSON Object of DNS Setting
	DNSSettings *shared.DNSSettings
	StatusCode  int
	RawResponse *http.Response
}
