// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type PutAPIUsersUserIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type PutAPIUsersUserIDRequest struct {
	// User update
	UserRequest *shared.UserRequest `request:"mediaType=application/json"`
	// The unique identifier of a user
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type PutAPIUsersUserIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A User object
	User *shared.User
}
