// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"netbird/internal/sdk/pkg/models/shared"
)

type PutAPIPeersPeerIDSecurity struct {
	BearerAuth *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	TokenAuth  *string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

type PutAPIPeersPeerIDRequest struct {
	// update a peer
	PeerRequest *shared.PeerRequest `request:"mediaType=application/json"`
	// The unique identifier of a peer
	PeerID string `pathParam:"style=simple,explode=false,name=peerId"`
}

type PutAPIPeersPeerIDResponse struct {
	ContentType string
	// A Peer object
	Peer        *shared.Peer
	StatusCode  int
	RawResponse *http.Response
}
